### ISSUE TITLE
README entry for how to instrument a cache 

### ISSUE THREAD

**Issue by ash211** [palantir/tritium#1895]
The README currently talks about how tritium is good for instrumenting a cache, but not how to do it.

I think the main points to hit are:
- Call `CaffeineCacheStats.registerCache()` [here](https://github.com/palantir/tritium/blob/d787bbbe676dcad82edeee1db59e66d868b2aca1/tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStats.java#L70-L80)
- if you have a common `TaggedMetricRegistry` like one from witchcraft, pass that as the parameter

**Comment by schlosna** [comment]
Thanks @ash211 , I definitely agree the README could be spruced up with some solid examples. Would you be interested in submitting a PR 😄 ?

**Comment by ash211** [comment]
Also I think you need to call `.recordStats()` on the CaffeineCache.Builder

And then I'm not sure the format that the metrics are emitted in either

**Comment by ash211** [comment]
Do we have any recommendations for the metric name parameter to `registerCache()`?  I see a mix of `someString` and `MetricRegistry.getName(getClass(), "someString")`

**Comment by ash211** [comment]
Also for the README, something like:
> For Palantirians, search for the internal "Caffeine Cache" dashboard to view the results.

**Comment by schlosna** [comment]
Should be resolved by https://github.com/palantir/tritium/pull/1897
