### ISSUE TITLE
io.dropwizard.metrics:metrics-core should be "api" dependency

### ISSUE THREAD

**Issue by uschi2000** [palantir/tritium#274]
io.dropwizard.metrics:metrics-core is currently an `implementation` dependency, although concepts like `Timer` are exposed through Tritium API, e.g., in TaggedMetricsRegistry.

**Comment by uschi2000** [comment]
@ellisjoe @schlosna

**Comment by schlosna** [comment]
Hey @uschi2000 , `tritium-metrics` does currently [declare `api 'io.dropwizard.metrics:metrics-core'`](https://github.com/palantir/tritium/blob/4db0d15/tritium-metrics/build.gradle#L11), though it wasn't declared as an `api` dependency in `tritium-lib`, `tritium-caffeine`, or `tritium-registry`, so created #275 to make this explicit for consumers.

**Comment by schlosna** [comment]
Also, curious if there is a better dependency linting mechanism as the baseline `com.palantir.baseline-exact-dependencies` flags some odd things in tritium, see https://github.com/palantir/tritium/pull/200 where I was testing out  and https://github.com/palantir/gradle-baseline/issues/567
