### ISSUE TITLE
FR: alternative Gauge API that doesn't require a lambda (e.g. SettableGauge)

### ISSUE THREAD

**Issue by iamdanfox** [palantir/tritium#278]
Gauges are different from all other metric types in that sampling them is a 'pull' operation that involves running a user-provided lambda, which could (and in practise often does) end up causing potentially very slow network requests.

This is bad because it means dumping an entire metrics registry can take a wildly unpredictable amount of time (e.g. 16 minutes).

## Proposal

Invent some kind of `SettableGauge<T>` class, expose it in both regular & tagged metric registries.

- We might want to also store the time at which a value was set, so that when the SettableGauge is sampled and we want to emit a metric.1 log line to disk, we can put an accurate timestamp next to the value we received.

Possibly worth making up specialized versions of this class for `long`, `integer` and `double`.

**Comment by uschi2000** [comment]
Is this something we should discuss upstream with the dropwizard folks?

**Comment by schlosna** [comment]
see also https://github.com/dropwizard/metrics/issues/1126

**Comment by iamdanfox** [comment]
Closing out because we changed our reporting methodology so that each gauge reporting is scheduled independent of each other gauge, meaning that a single slow gauge can't block others.
