### ISSUE TITLE
Reflective error in SafepointMetrics when running in Java 11

### ISSUE THREAD

**Issue by mglazer** [palantir/tritium#482]
## What happened?

I see this error when running with Java 11:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.palantir.tritium.metrics.jvm.SafepointMetrics (file:/opt/palantir/.binaries/tiles/4.38.0/tiles-4.38.0/service/lib/tritium-metrics-jvm-0.15.8-rc1.jar) to method sun.management.ManagementFactoryHelper.getHotspotRuntimeMBean()
WARNING: Please consider reporting this to the maintainers of com.palantir.tritium.metrics.jvm.SafepointMetrics
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## What did you want to happen?

Not display that error since in a future release this may break more.

**Comment by iamdanfox** [comment]
Think this is actually in the open-source palantir/tritium repo: https://github.com/palantir/tritium/blob/develop/tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/SafepointMetrics.java

**Comment by iamdanfox** [comment]
To make this go away, I think either tritium needs a `module-info.java` file declaring that it is going to reflectively access the `sun.management.ManagementFactoryHelper` class (which is in the `java.management` module), or we'd need to add some jvm args like:

```
--add-opens java.management/sun.management=ALL-UNNAMED
```

to all running WC services.
