### ISSUE TITLE
API break leads to diamond dependencies

### ISSUE THREAD

**Issue by uschi2000** [palantir/tritium#54]
Looks like `com/palantir/tritium/event/InvocationEventHandler` moved to `com/palantir/tritium/event/api/InvocationEventHandler`. This results in a Tritium (and app-server) upgrade boundary for any AtlasDB consumer: https://github.com/palantir/atlasdb/blob/develop/atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java#L32

**Comment by schlosna** [comment]
Closed by #55

**Comment by schlosna** [comment]
Fixed in release 0.8.1
