### ISSUE TITLE
Supporting Caffeine caches in MetricRegistries#registerCache

### ISSUE THREAD

**Issue by swarelle** [palantir/tritium#765]
## What happened?

I'm working on a change that uses a Caffeine cache instead of a Guava cache because of its ability to handle cases where keys may not be mapped to a value at all. I noticed that MetricRegistries#registerCache only takes a Guava cache, and I'm not sure if I can safely cast the Caffeine cache into a Guava one to use this method.

## What did you want to happen?

Can MetricRegistries support registering a Caffeine cache too?

**Comment by carterkozak** [comment]
Hi Ellen,

The [tritium-caffeine](https://github.com/palantir/tritium/tree/develop/tritium-caffeine) module should do what you describe. It’s a little less discoverable in order to avoid forcing a caffeine dependency on all tritium users, sorry about that.

**Comment by schlosna** [comment]
We can improve our docs here for the common usages, especially as [gradle-baseline encourages Caffeine cache usage over Guava caches](https://github.com/palantir/gradle-baseline/pull/317).

As @carterkozak mentioned, `import com.palantir.tritium.metrics.caffeine.CaffeineCacheStats;` from the tritium-caffeine module and then use as below:

https://github.com/palantir/tritium/blob/7f04dc0209f89ec6ec67199d0b3121909750c7e4/tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java#L71-L73

**Comment by carterkozak** [comment]
Closing this out as it appears to be resolved.
